### ISSUE TITLE
Error for (const privateKey of privateKeys) {

### ISSUE THREAD

**Issue by naufaljct48** [dante4rt/particle-testnet-bot#1]
E:\Airdrop\particle-testnet-bot\index.js:19
  for (const privateKey of privateKeys) {
                           ^

TypeError: privateKeys is not iterable
    at main (E:\Airdrop\particle-testnet-bot\index.js:19:28)
    at Object.<anonymous> (E:\Airdrop\particle-testnet-bot\index.js:145:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

Please fix: const privateKeys = JSON.parse(fs.readFileSync("privateKeys.json"));
To: const privateKeysData = fs.readFileSync('privateKeys.json', 'utf8');
  const { privateKeys } = JSON.parse(privateKeysData);
![image](https://github.com/dante4rt/particle-testnet-bot/assets/30202760/3557df3d-9769-441b-9e16-6a2ea6e5c9cf)

**Comment by dante4rt** [comment]
> E:\Airdrop\particle-testnet-bot\index.js:19 for (const privateKey of privateKeys) { ^
> 
> TypeError: privateKeys is not iterable at main (E:\Airdrop\particle-testnet-bot\index.js:19:28) at Object. (E:\Airdrop\particle-testnet-bot\index.js:145:1) at Module._compile (node:internal/modules/cjs/loader:1358:14) at Module._extensions..js (node:internal/modules/cjs/loader:1416:10) at Module.load (node:internal/modules/cjs/loader:1208:32) at Module._load (node:internal/modules/cjs/loader:1024:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) at node:internal/main/run_main_module:28:49
> 
> Please fix: const privateKeys = JSON.parse(fs.readFileSync("privateKeys.json")); To: const privateKeysData = fs.readFileSync('privateKeys.json', 'utf8'); const { privateKeys } = JSON.parse(privateKeysData); ![image](https://private-user-images.githubusercontent.com/30202760/342034010-3557df3d-9769-441b-9e16-6a2ea6e5c9cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjU2ODUsIm5iZiI6MTcxOTEyNTM4NSwicGF0aCI6Ii8zMDIwMjc2MC8zNDIwMzQwMTAtMzU1N2RmM2QtOTc2OS00NDFiLTllMTYtNmEyZWE2ZTVjOWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDA2NDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MTc2OGVmYjc2YTM3MTI4NmE2OTczNzQxM2RlYTUwMWM5OTFjMzVjZDM1YjllODI0NTAyZTY5YjU4OGEzNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p-V7DLiP6sPb_Lw-__eYt4AAX1w-TRHeYguCPOk2Urk)

Thanks for pointing out the issue, but I believe you provided an incorrect JSON format.

**Wrong:**
```
{
    "key1": "0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    "key2": "0xfedcba9876543210fedcba9876543210fedcba9876543210fedcba987654321"
}
```

**Correct:**
```
[
    "another_private_key_here_1",
    "another_private_key_here_2"
]
```
